[package]
name = "codebasecontextualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
walkdir = "2.3"
tokio = { version = "1", features = ["full"] }
futures = "0.1"
